### ISSUE TITLE
can you make .ipynb file with github all files path or i have to add your files to tensorflow-master

### ISSUE THREAD

**Issue by kushu9999** [ShivamShrirao/garbage_detection#1]

**Comment by ShivamShrirao** [comment]
Are you talking about the files for training the ssd net ?

**Comment by kushu9999** [comment]
I have to create same thing as my task in company in my internship, can you
help me to make it or can you make on all things on Google colab with each
and every file with all tensorflow models training pre-trained models etc
etc

I'll be very thankful to you it'll save my internship and I've to submit
till today night , today is last date for me

**Comment by ShivamShrirao** [comment]
If you see the garbage_detection.ipynb file. It's the file from colab. It has almost everything you need. It downloads the required repos and libraries too. Just a few files need to be put from repo. You can easily understand that by reading the cells a bit. See if that helps

**Comment by kushu9999** [comment]
In my code i found error on No module named 'nets'

**Comment by ShivamShrirao** [comment]
On which line/cell exactly ?

**Comment by ShivamShrirao** [comment]
It's due to the path in environment. See the 3rd or 4th cell. I have set up PYTHONPATH. Execute that first.

**Comment by kushu9999** [comment]
>
>
Can you send me train and test record file

>

**Comment by ShivamShrirao** [comment]
Well okay, I'm currently outside so will take time. Btw should I mail u ?

**Comment by kushu9999** [comment]
Can you send me now ? Means tomorrow
